### ISSUE TITLE
Uppload for Angular

### ISSUE THREAD

**Issue by beeman** [elninotech/uppload#9]
Uppload looks great, thanks for sharing it's code!

I would love to use it in my Angular app and I was wondering if this is something you plan on building.

If not, I might take a look to see if I can add it to the project.

**Comment by AnandChowdhary** [comment]
Hi Bram! We absolutely want to have a wrapper for Angular as well (we figured since our team personally used Vue and React more often, we'll start there). If you're interested, you should definitely take it up!

As you are from the Vue and React wrappers, they're just a single file wrapping the user's configuration and on upload and on error functions around the plugin. We'd love for you to contribute the Angular wrapper! 😁

**Comment by beeman** [comment]
Awesome @AnandChowdhary, thanks!

I just created a [small proof of concept](https://github.com/beeman/uppload-angular-demo/tree/master/projects/uppload) and it seems to be quite straightforward to implement it 👍

The build process for Angular libraries is quite involved but it's nicely abstracted by [ng-packagr](https://github.com/dherges/ng-packagr). It probably makes most sense to run that build command after the main webpack build from this repo, that way we don't have to reproduce everything ng-packagr does. 

Because most Angular projects use TypeScript it might make sense to publish typings with the main `uppload` module. For now I'll just define them manually and ship 'em with the `uppload-angular` library.


#### Todo:

- [ ] support all configuration parameters
- [ ] support all properties
- [ ] support all events
- [ ] support all methods
- [ ] implement typings file
- [ ] merge into [elninotech/uppload](https://github.com/elninotech/uppload)
- [ ] create demo app / stackblitz

**Comment by beeman** [comment]
It looks like most of it works as expected, great simple API 👍

https://stackblitz.com/edit/uppload-angular?embed=1&file=src/app/app.component.ts

You should have an invite for [uppload-angular](https://www.npmjs.com/package/uppload-angular) on npm, feel free to remove me from the collaborators once it landed in the repo.

I'll create a pull request tomorrow :)

**Comment by AnandChowdhary** [comment]
It looks wonderful! Looking forward to your pull request!
